# Generated by Django 5.1.3 on 2025-01-08 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=40)),
                ('Description', models.CharField(max_length=100)),
                ('Instructor', models.CharField(max_length=50)),
                ('Rating', models.IntegerField()),
            ],
        ),
    ]
